services:
    blougly:
        build:
            context: .
            dockerfile: Dockerfile
        init: true
        volumes:
            - .:/app
            - ../resources:/app/storage/resources
            - ../public:/app/storage/public
        working_dir: /app
        container_name: blougly
